services:
  hello:
    image: nginx:alpine
    ports:
      - "8080:80"
    configs:
      - source: index
        target: /usr/share/nginx/html/index.html
    restart: unless-stopped

configs:
  index:
    content: "hello world\n"
